name: Self Hosted Runners Practice

env:
  TraderName: "Harshad Mehta"
  Designation: "The Big Bull of Dalal Street"
  Message: "Welcome to the Indian Stock Exchange"

on: 
  push: 
    branches: ["main", "master"]

  workflow_dispatch:


jobs:
  demojob1:
    runs-on: self-hosted
    steps: 
    - uses: actions/checkout@v3

    - name: Run a one-line script 
      run: echo "Hello $TraderName $Designation"

    - name: Run a multi-line script
      run: |
        echo "In self hosted runner"
        echo "Hello $TraderName"
        echo $Message
